build: false
shallow_clone: true
platform: x86
clone_folder: c:\projects\isolate\symfony-bundle

init:
  - SET COMPOSER_NO_INTERACTION=1
    
install:
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_apc.dll
  - echo extension_dir=ext >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd c:\projects\isolate\symfony-bundle
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - php composer.phar update --prefer-source --no-progress --ansi

test_script:
  - cd c:\projects\isolate\symfony-bundle
  - bin\phpunit.bat