services:
  isolate.lazy_objects.wrapper.proxy.adapter.configuration:
    class: ProxyManager\Configuration
    calls:
      - ["setProxiesTargetDir", [%isolate.lazy_objects.proxy_dir%]]

  isolate.lazy_objects.wrapper.proxy.adapter.factory:
    class: Isolate\LazyObjects\Proxy\Adapter\OcramiusProxyManager\Factory\LazyObjectsFactory
    public: false

  isolate.lazy_objects.definition.collection:
    class: Isolate\Symfony\IsolateBundle\LazyObject\DefinitionCollection
    arguments:
      - [] # replaced by EntityLazyObjectDefinitionCompilerPass
    public: false

  isolate.lazy_objects.wrapper.proxy.factory:
    class: Isolate\LazyObjects\Proxy\Adapter\OcramiusProxyManager\Factory
    arguments:
      - @isolate.lazy_objects.wrapper.proxy.adapter.factory
    public: false

  isolate.lazy_objects.wrapper:
    class: Isolate\LazyObjects\Wrapper
    arguments:
      - @isolate.lazy_objects.wrapper.proxy.factory
      - @isolate.lazy_objects.definition.collection
